import type { EffectId, EffectMeta } from "@/features/birthday-effects/effects";

export const EFFECTS: EffectMeta[] = [
  {
    id: "glow-zoom",
    label: "Brilho Zoom",
    description: "Explosão de luz cinematográfica",
    icon: "✨",
  },
  {
    id: "floating-letters",
    label: "Letras Flutuantes",
    description: "Letras montando a frase",
    icon: "🪶",
  },
  { id: "neon-flicker", label: "Placa Neon", description: "Neon piscando em festa", icon: "💡" },
  { id: "balloon-letters", label: "Balões", description: "Frase levada por balões", icon: "🎈" },
  {
    id: "confetti-celebration",
    label: "Chuva de Confete",
    description: "Explosão de festa",
    icon: "🎊",
  },
  { id: "fireworks-reveal", label: "Fogos", description: "Revelação iluminada", icon: "🎆" },
  { id: "cake-surprise", label: "Bolo Surpresa", description: "Velas acendem a frase", icon: "🎂" },
  { id: "gift-box", label: "Caixa de Presente", description: "Abertura mágica", icon: "🎁" },
  {
    id: "particle-formation",
    label: "Partículas",
    description: "Pontos formando letras",
    icon: "✦",
  },
  {
    id: "explosion-rebuild",
    label: "Explode e Volta",
    description: "Quebra e reconstrói",
    icon: "💥",
  },
  { id: "ribbon-swipe", label: "Fita de Luz", description: "Rastro revela a frase", icon: "🎀" },
  { id: "spark-trail", label: "Escrita Mágica", description: "Desenhado por faíscas", icon: "🪄" },
  {
    id: "star-rain",
    label: "Chuva de Estrelas",
    description: "Estrelas caem em cascata",
    icon: "⭐",
  },
  {
    id: "pulse-celebration",
    label: "Batida do Coração",
    description: "Pulsa no ritmo",
    icon: "❤️",
  },
  { id: "bounce-text", label: "Pulo Feliz", description: "Entrada elástica", icon: "🏀" },
  { id: "rotating-letters", label: "Giro 3D", description: "Letras girando no espaço", icon: "🌀" },
  {
    id: "soft-elegant-fade",
    label: "Fade Elegante",
    description: "Brilho suave e luxuoso",
    icon: "🕯️",
  },
  {
    id: "dual-language",
    label: "Feliz em Dobro",
    description: "Frase renasce em brilho",
    icon: "🌐",
  },
  { id: "split-merge", label: "Divide e Junta", description: "Palavras se encontram", icon: "↔️" },
  {
    id: "ultimate-finale",
    label: "Finale Completo",
    description: "Todos os brilhos juntos",
    icon: "👑",
  },
  // Novos
  {
    id: "liquid-metal",
    label: "Ouro Líquido",
    description: "Metal derretido revelando",
    icon: "🪙",
  },
  { id: "galaxy-portal", label: "Portal Galáxia", description: "Viagem pelo espaço", icon: "🌌" },
  {
    id: "typewriter-glitch",
    label: "Glitch Digital",
    description: "Decodificação futurista",
    icon: "⌨️",
  },
  {
    id: "champagne-pop",
    label: "Brinde Champanhe",
    description: "Bolhas e rolha no ar",
    icon: "🍾",
  },
  { id: "holographic-shift", label: "Holograma", description: "Brilho iridescente", icon: "🪩" },
  {
    id: "petal-shower",
    label: "Chuva de Pétalas",
    description: "Pétalas românticas caindo",
    icon: "🌸",
  },
  {
    id: "kinetic-typography",
    label: "Tipografia Cinética",
    description: "Movimento forte nas letras",
    icon: "🎬",
  },
  { id: "aurora-veil", label: "Véu Aurora", description: "Luzes dançando no céu", icon: "🌠" },
  {
    id: "spotlight-reveal",
    label: "Luz de Palco",
    description: "Holofotes varrem a frase",
    icon: "🔦",
  },
  {
    id: "cosmic-orbit",
    label: "Órbita Cósmica",
    description: "Planetas rodeiam o desejo",
    icon: "🪐",
  },
  { id: "candle-wish", label: "Pedido na Vela", description: "Chamas sobem brilhando", icon: "🕯️" },
  {
    id: "laser-scan",
    label: "Varredura Laser",
    description: "Letras em feixes neon",
    icon: "⚡",
  },
  {
    id: "photo-flash",
    label: "Flash de Foto",
    description: "Memória em estalo de luz",
    icon: "📸",
  },
  {
    id: "samba-burst",
    label: "Explosão Samba",
    description: "Festa em ritmo brasileiro",
    icon: "🎉",
  },
];

export const EFFECT_IDS: EffectId[] = EFFECTS.map((e) => e.id);
